import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Search,MapPin,CalendarDays,Heart,Truck,BookOpen,Gamepad2,Headphones,ShieldCheck,Tag,Play,ArrowRight,Quote,Menu,X}from'lucide-react';
import'./styles.css';

const A='/assets/';
const pages=[['Home','/'],['Events','/events'],['Stories','/stories'],['Community Box','/community-box']];
function route(){return location.pathname.replace(/\/$/,'')||'/'}
function go(e,path){e.preventDefault();history.pushState({},'',path);dispatchEvent(new PopStateEvent('popstate'));scrollTo({top:0,behavior:'smooth'})}
function Header({active}){const[open,setOpen]=useState(false);return <header><a href="/" onClick={e=>go(e,'/')} className="brand">Conscious Connections</a><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{pages.map(([n,p])=><a key={p} className={active===p?'active':''} href={p} onClick={e=>{setOpen(false);go(e,p)}}>{n}</a>)}<a href="#join" className="nav-cta">Join Community</a></nav></header>}
function Footer(){return <footer><div><div className="brand">Conscious Connections</div><p>Building a world where everyone belongs,<br/>one connection at a time.</p></div><div><b>Community</b><a>About Us</a><a>Host an Event</a><a>Values</a></div><div><b>Support</b><a>Contact</a><a>Privacy Policy</a><a>Guidelines</a></div><div><b>Stay connected</b><p>© 2024 Conscious Connections.<br/>A radically welcoming space.</p></div></footer>}
function Photo({src='community.jpg',className=''}){return <img className={'photo '+className} src={A+src} alt="Conscious Connections community"/>}
function Home(){const[email,setEmail]=useState('');const[done,setDone]=useState(false);return <><Header active="/"/><main>
 <section className="home-hero"><div><span className="pill">LGBTQ+ Community Sanctuary</span><h1>Where Every<br/>Connection Feels<br/>Like <em>Golden Hour.</em></h1><p>Step into a vibrant, unapologetically joyful space designed for queer women and non-binary individuals to find their tribe, share stories, and grow together.</p><div className="actions"><a href="/events" onClick={e=>go(e,'/events')} className="btn">Explore Events</a><a href="/stories" onClick={e=>go(e,'/stories')} className="btn outline">Our Story</a></div></div><div className="hero-media"><Photo/><div className="member-badge"><Heart size={17}/> 5k+ Members<br/><small>Joined this month</small></div></div></section>
 <section className="box-preview"><h2>The Community Box</h2><p>Discover the essentials curated to make your community journey safe, fun, and meaningful.</p><div className="bento">{[[BookOpen,'Weekly Magazine','Deep dives into queer culture, art, and personal growth stories.'],[Gamepad2,'Game Cards','Ice-breakers for any mood.'],[Headphones,'Helpline','24/7 moderated safe space.'],[ShieldCheck,'Wellness Tips','Mental health by us, for us.'],[Tag,'Pride Stickers','Digital flair for your profile.'],[Heart,'Community Badge','Identify as a founding member.']].map(([I,t,d],i)=><article className={'tile t'+i} key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
 <section className="testimonial"><Photo src="workshop.jpg"/><div><h2>Voices of Connection</h2><Quote/><blockquote>“I never felt like I truly belonged anywhere until I found this community. It's more than just an app; it's the safety and warmth I've been searching for my whole life.”</blockquote><b>— Maya, Community Member</b></div></section>
 <section className="host"><div><h2>Host Your Own <em>Workshop</em></h2><p>Have a passion for ceramics, poetry, or coding? Share your skills with the community.</p><ul><li>Curated workshop guides and templates</li><li>Direct access to our booking platform</li><li>Marketing support to reach local members</li></ul><button className="btn">Become a Host</button></div><div className="mini-grid"><Photo src="quiet-table.png"/><Photo src="collaboration.png"/><Photo src="table.png"/><Photo src="feedback.png"/></div></section>
 <section className="signup" id="join"><h2>Ready to find your circle?</h2><p>Join the waitlist for our next seasonal box and get exclusive early access to community events.</p>{done?<strong>Welcome to the circle! Check your inbox.</strong>:<form onSubmit={e=>{e.preventDefault();if(email)setDone(true)}}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email" required/><button>Sign Up Now</button></form>}</section>
 </main><Footer/></>}

const events=[['Queer Art Night','Creative','Sun, Oct 12 • 6:30 PM • East Village','workshop.jpg'],['Trans Joy Circle','Support','Wed, Oct 15 • 7:00 PM • Remote / SF','collaboration.png'],['Sapphic Book Club','Social','Sat, Oct 18 • 11:00 AM • Oakland','quiet-table.png'],['Mindful Movement','Workshops','Tue, Oct 21 • 6:00 PM • Berkeley','feedback.png'],['Queer Cooking Collab','Social','Fri, Oct 24 • 5:30 PM • Mission District','table.png'],['Sunset Trail Walk','Social','Sun, Oct 26 • 4:00 PM • Marin Headlands','community.jpg']];
function Events(){const[filter,setFilter]=useState('All');const[q,setQ]=useState('');const shown=useMemo(()=>events.filter(e=>(filter==='All'||e[1]===filter)&&e[0].toLowerCase().includes(q.toLowerCase())),[filter,q]);return <><Header active="/events"/><main className="events-page"><section className="page-intro"><h1>Upcoming Gatherings</h1><p>Find your circle in local safe spaces designed for LGBTQ+ women and non-binary individuals. Every event is a step toward radical belonging.</p><div className="filters"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by city, activity, or vibe..."/></label>{['All','Social','Workshops','Creative','Support'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div></section><section className="featured"><Photo src="community.jpg"/><div><span className="pill">★ Featured Event</span><h2>Pride Summer Picnic</h2><p><CalendarDays/> Saturday, June 15th • 2:00 PM</p><p><MapPin/> Golden Gate Park, San Francisco</p><p>Join us for an afternoon of community, snacks, and sunset vibes. Whether you're new to the city or a long-time local, this picnic is all about expanding our circles.</p><button className="btn">View Details</button></div></section><section><h2>Nearby Experiences</h2><div className="event-grid">{shown.map(([t,c,d,img])=><article className="event-card" key={t}><div className="card-photo"><Photo src={img}/><span>{c}</span></div><h3>{t}</h3><p>{d}</p><p>Bring your curiosity and meet kind people in a welcoming community space...</p><div><span className="avatars">● ● ●</span><button>RSVP</button></div></article>)}</div>{shown.length===0?<p className="empty">No gatherings match your search yet.</p>:null}</section><section className="wide-cta"><div><h2>Don't see what you're looking for?</h2><p>Have an idea for a niche gathering or regular social hour? We'll help you bring it to life.</p></div><button>Host an Event</button></section></main><Footer/></>}

const stories=[['David: Finding Flow in Chaos','ARTISTIC GROWTH','workshop.jpg'],['The Mentorship Loop','MENTORSHIP','collaboration.png'],['Legacy of the Pen','PERSONAL REFLECTION','community.jpg']];
function Stories(){const[more,setMore]=useState(false);return <><Header active="/stories"/><main className="stories-page"><section className="story-hero"><span>SHARED JOURNEYS</span><h1>Voices of Connection</h1><p>Every thread in our tapestry is a story. Discover the raw, transformative experiences of our members—stories of belonging, creative sparks, and the quiet power of showing up.</p></section><section className="feature-story"><div className="quote-photo"><Photo src="quiet-table.png"/><aside><Quote/>“I found more than a hobby; I found my mirror in others.”</aside></div><div><span>FEATURED STORY</span><h2>The Quiet Art of Listening: Maya’s Journey</h2><p>Maya first walked into a Conscious Connections workshop three years ago, hesitant and carrying the weight of a busy city life. What she found wasn't just a structured activity, but a space that breathed.</p><a>READ THE FULL STORY <ArrowRight/></a></div></section><section className="chronicles"><h2>Community Chronicles</h2><p>Glimpses into the lives that shape our space.</p><div className="story-grid">{[...stories,...(more?stories:[])].map(([t,c,img],i)=><article key={t+i}><Photo src={img}/><div><span>{c}</span><h3>{t}</h3><p>Discover how one authentic connection became the beginning of something meaningful...</p><small>● &nbsp; Published Sep {28-i}, 2024</small></div></article>)}</div>{!more?<button className="load" onClick={()=>setMore(true)}>Load More Stories</button>:null}</section><section className="story-cta"><h2>Your Voice is the Missing Piece</h2><p>Every journey matters. Sharing your story helps others find their way.</p><button>Tell Your Story</button></section></main><Footer/></>}

function CommunityBox(){return <><Header active="/community-box"/><main className="community-page"><section className="community-hero"><div><span className="pill">Curated Connection</span><h1>The Community<br/>Box</h1><p>A seasonal collection of tactile tools for self-reflection, joyful belonging, and conscious connection. Delivered to your door.</p><button className="btn">Get the Next Box <Truck/></button></div><Photo src="community-box.png"/></section></main><Footer/></>}
function App(){const[path,setPath]=useState(route());React.useEffect(()=>{const fn=()=>setPath(route());addEventListener('popstate',fn);return()=>removeEventListener('popstate',fn)},[]);return path==='/events'?<Events/>:path==='/stories'?<Stories/>:path==='/community-box'?<CommunityBox/>:<Home/>}
createRoot(document.getElementById('root')).render(<App/>);
